# -*- coding: utf-8 -*-
"""Movie Ratings Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjDnGm2hdouvfZYenyGA_8PUvkWgGdwc
"""

# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load movie dataset

df = pd.read_csv("movie_analysis_dataset.csv")

# Display first 5 rows
df.head()

# Check dataset information

df.info()

# Generate statistical summary

df.describe()

# Check missing values in each column

df.isnull().sum()

# Remove rows with missing values (safe practice)

df = df.dropna()

# Rating statistics

print("Rating Mean:", np.mean(df["Rating"]))
print("Rating Median:", np.median(df["Rating"]))
print("Rating Standard Deviation:", np.std(df["Rating"]))

# Budget statistics

print("Budget Mean:", np.mean(df["Budget"]))
print("Budget Median:", np.median(df["Budget"]))
print("Budget Standard Deviation:", np.std(df["Budget"]))

# Revenue statistics

print("Revenue Mean:", np.mean(df["Revenue"]))
print("Revenue Median:", np.median(df["Revenue"]))
print("Revenue Standard Deviation:", np.std(df["Revenue"]))

# Average rating by genre

genre_rating = df.groupby("Genre")["Rating"].mean()

genre_rating

# Average rating by director

director_rating = df.groupby("Director")["Rating"].mean()

director_rating

# Average rating by year

year_rating = df.groupby("Year")["Rating"].mean()

year_rating

# Bar Plot: Average Rating by Genre and Director

plt.figure(figsize=(12,5))

# Genre Ratings
plt.subplot(1, 2, 1)
plt.bar(genre_rating.index, genre_rating.values)
plt.title("Average Rating by Genre")
plt.xlabel("Genre")
plt.ylabel("Average Rating")

# Director Ratings
plt.subplot(1, 2, 2)
plt.bar(director_rating.index, director_rating.values)
plt.title("Average Rating by Director")
plt.xlabel("Director")
plt.ylabel("Average Rating")

plt.tight_layout()

plt.savefig("genre_director_rating_barplot.png")

plt.show()

# Line Plot: Average Ratings Over Years

plt.figure(figsize=(8,5))

plt.plot(
    year_rating.index,
    year_rating.values,
    marker="o"
)

plt.title("Average Movie Ratings Over Years")
plt.xlabel("Year")
plt.ylabel("Average Rating")

plt.grid(True)

plt.savefig("year_rating_trend.png")

plt.show()

# Scatter Plot: Budget vs Rating

plt.figure(figsize=(8,5))

plt.scatter(
    df["Budget"],
    df["Rating"]
)

plt.title("Budget vs Rating")
plt.xlabel("Budget")
plt.ylabel("Rating")

plt.savefig("budget_vs_rating.png")

plt.show()

# Scatter Plot: Revenue vs Rating

plt.figure(figsize=(8,5))

plt.scatter(
    df["Revenue"],
    df["Rating"]
)

plt.title("Revenue vs Rating")
plt.xlabel("Revenue")
plt.ylabel("Rating")

plt.savefig("revenue_vs_rating.png")

plt.show()

# Top 10 Rated Movies

top_movies = df.nlargest(10, "Rating")

plt.figure(figsize=(10,5))

plt.barh(
    top_movies["Movie"],
    top_movies["Rating"]
)

plt.title("Top Rated Movies")
plt.xlabel("Rating")
plt.ylabel("Movie")

plt.savefig("top_rated_movies.png")

plt.show()

"""# Conclusion

This project analyzed movie data using Pandas, NumPy, and Matplotlib.

Key Findings:

- Movie ratings were analyzed using statistical measures such as mean, median, and standard deviation.
- Genre-wise and director-wise grouping revealed differences in average ratings.
- Rating trends over the years were examined using line plots.
- Relationships between budget, revenue, and ratings were explored using scatter plots.
- Top-rated movies were identified through ranking analysis.

This project demonstrates data cleaning, statistical analysis, grouping operations, and data visualization techniques using Python.
"""